---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
    - tag
    - promote
    - rollback

steps:
- name: publish-docker-image
  pull: always
  image: plugins/docker
  settings:
    repo: cs3org/cs3apis
    tags: latest
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    custom_dns:
      - 128.142.17.5
      - 128.142.16.5
